/*dhtmlxGrid v.1.4 build 70813 Professional Edition
Copyright Scand LLC http://www.scbr.com
To use this component please contact info@scbr.com to obtain license
*/
 

//dhtmlXGridObject.prototype.enableAutoSizeSaving = function(name,cookie_param){this.attachEvent("onResizeEnd",function(){this.saveSizeToCookie(name,cookie_param) })};dhtmlXGridObject.prototype.enableAutoHiddenColumnsSaving = function(name,cookie_param){this.setColumnHiddenSSC=this.setColumnHidden;this.setColumnHidden=function(){this.setColumnHiddenSSC.apply(this,arguments);this.saveHiddenColumnsToCookie(name,cookie_param)}};dhtmlXGridObject.prototype.enableSortingSaving = function(name,cookie_param){this.attachEvent("onBeforeSorting",function(){var that=this;window.setTimeout(function(){that.saveSortingToCookie(name,cookie_param)},1);return true})};dhtmlXGridObject.prototype.enableOrderSaving = function(name,cookie_param){this.attachEvent("onAfterCMove",function(){this.saveOrderToCookie(name,cookie_param);this.saveSizeToCookie(name,cookie_param)})};dhtmlXGridObject.prototype.enableAutoSaving = function(name,cookie_param){this.enableOrderSaving(name,cookie_param);this.enableAutoSizeSaving(name,cookie_param);this.enableSortingSaving(name,cookie_param)};dhtmlXGridObject.prototype.saveSizeToCookie=function(name,cookie_param){if (this.cellWidthType=='px')var z=this.cellWidthPX.join(",");else
// var z=this.cellWidthPC.join(",");var z2=(this.initCellWidth||(new Array)).join(",");this.setCookie(name,cookie_param,0,z);this.setCookie(name,cookie_param,1,z2)};dhtmlXGridObject.prototype.saveHiddenColumnsToCookie=function(name,cookie_param){this.setCookie(name,cookie_param,4,(this._hrrar||[]).join(",").replace(/display:none;/g,"1"))};dhtmlXGridObject.prototype.loadHiddenColumnsFromCookie=function(name){var z=this._getCookie(name,4);z=(z||"").split(",");if (z.length>this._cCount)return;for (var i=0;i < z.length;i++)this.setColumnHidden(i,(z[i]?true:false))};dhtmlXGridObject.prototype.saveSortingToCookie=function(name,cookie_param){this.setCookie(name,cookie_param,2,(this.getSortingState()||[]).join(","))};dhtmlXGridObject.prototype.loadSortingFromCookie=function(name){var z=this._getCookie(name,2);z=(z||"").split(",");if (z.length>1 && z[0]<this._cCount){this.sortRows(z[0],null,z[1]);this.setSortImgState(true,z[0],z[1])}};dhtmlXGridObject.prototype.saveOrderToCookie=function(name,cookie_param){this.setCookie(name,cookie_param,3,(this._c_order||[]).join(","))};dhtmlXGridObject.prototype.loadOrderFromCookie=function(name){var z=this._getCookie(name,3);z=(z||"").split(",");if (z.length>1 && z.length<=this._cCount){for (var i=0;i<z.length;i++)if ((!this._c_order && z[i]!=i)||(this._c_order && z[i]!=this._c_order[i])){var t=z[i];if (this._c_order)for (var j=0;j<this._c_order.length;j++){if (this._c_order[j]==z[i]){t=j;break}};this.moveColumn(t*1,i)}}};dhtmlXGridObject.prototype.loadSizeFromCookie=function(name){var z=this._getCookie(name,1);if (z)this.initCellWidth=z.split(",");var z=this._getCookie(name,0);if ((z)&&(z.length)){if (!this._fake && this._hrrar)for (var i=0;i<z.length;i++)if ( this._hrrar[i])z[i]=0;if (this.cellWidthType=='px')this.cellWidthPX=z.split(",");else
// this.cellWidthPC=z.split(",")};this.setSizes();return true};dhtmlXGridObject.prototype.clearConfigCookie=function(name){if (!name)name=this.entBox.id;this.setCookie("gridSettings"+name,"")};dhtmlXGridObject.prototype.clearSizeCookie=dhtmlXGridObject.prototype.clearConfigCookie;dhtmlXGridObject.prototype.setCookie=function(name,cookie_param,pos,value) {if (!name)name=this.entBox.id;var t=this.getCookie(name);t=(t||"||||").split("|");t[pos]=value;var str = "gridSettings"+name + "=" + t.join("|") + (cookie_param?(";"+cookie_param):"");document.cookie = str};dhtmlXGridObject.prototype.getCookie=function(name) {if (!name)name=this.entBox.id;name="gridSettings"+name;var search = name + "=";if (document.cookie.length > 0){var offset = document.cookie.indexOf(search);if (offset != -1){offset += search.length;var end = document.cookie.indexOf(";", offset);if (end == -1)end = document.cookie.length;return document.cookie.substring(offset, end)}}};dhtmlXGridObject.prototype._getCookie=function(name,pos) {return ((this.getCookie(name)||"||||").split("|"))[pos]};

 
dhtmlXGridObject.prototype.enableAutoSizeSaving = function(name,cookie_param){this.setOnResizeEnd(function(){this.saveSizeToCookie(name,cookie_param) });};dhtmlXGridObject.prototype.saveSizeToCookie=function(name,cookie_param){if (!name)name=this.entBox.id;if (this.cellWidthType=='px')var z=this.cellWidthPX.join(",");else
 var z=this.cellWidthPC.join(",");this.setCookie("gridSizeA"+name,z,cookie_param);var z=(this.initCellWidth||(new Array)).join(",");this.setCookie("gridSizeB"+name,z,cookie_param);return true;};dhtmlXGridObject.prototype.loadSizeFromCookie=function(name){if (!name)name=this.entBox.id;var z=this.getCookie("gridSizeB"+name);if (z)this.initCellWidth=z.split(",");var z=this.getCookie("gridSizeA"+name);if ((z)&&(z.length))
 if (this.cellWidthType=='px')this.cellWidthPX=z.split(",");else
 this.cellWidthPC=z.split(",");this.setSizes();return true;};dhtmlXGridObject.prototype.clearSizeCookie=function(name){if (!name)name=this.entBox.id;this.setCookie("gridSizeA"+name,"");this.setCookie("gridSizeB"+name,"");};dhtmlXGridObject.prototype.setCookie=function(name,value,cookie_param) {var str = name + "=" + value + (cookie_param?(";"+cookie_param):"");document.cookie = str;};dhtmlXGridObject.prototype.getCookie=function(name) {var search = name + "=";if (document.cookie.length > 0){var offset = document.cookie.indexOf(search);if (offset != -1){offset += search.length;var end = document.cookie.indexOf(";", offset);if (end == -1)end = document.cookie.length;return document.cookie.substring(offset, end);};};};
